version: '3.9'

services:
  app:
    build: .
    image: zenfiric/app:latest
    command: >
      sh -c "python manage.py wait_for_db &&
            # python manage.py makemigrations &&
            python manage.py migrate --database=${DATABASE:-default} &&
            python manage.py collectstatic --noinput &&
            # python manage.py unos_dana &&
            # python manage.py unos_meseci &&
            # python manage.py unos_narodnosti &&
            # python manage.py unos_veroispovesti &&
            # python manage.py unos_zanimanja &&
            # python manage.py unos_slava &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./crkva:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-devdb}
      - DB_SCHEMA=${DB_SCHEMA:-public}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-changeme}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-changeme}
