services:
  app:
    build: .
    image: zenfiric/app:latest
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-0}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA:-public}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}

volumes:
  static_data:
  postgres_data:
